# This Puppetfile was distributed with Dynaguppy
# https://github.com/Aethylred/dynaguppy
forge 'https://forgeapi.puppetlabs.com'

# The puppetlabs-stdlib has a compatibilty matrix
# https://github.com/puppetlabs/puppetlabs-stdlib#compatibility
# So be sure the appropriate version is specified for the installed
# version of puppet
mod 'puppetlabs-stdlib', '4.4.0'
mod 'puppetlabs-apt', '1.7.0'
mod 'puppetlabs-apache', '1.2.0'
mod 'puppetlabs-nodejs', '0.6.1'
mod 'puppetlabs-vcsrepo', '1.2.0'
mod 'puppetlabs-ruby', '0.4.0'
mod 'puppetlabs-mcollective', '2.0.0'
mod 'puppetlabs-puppetdb', '4.1.0'
mod 'puppetlabs-postgresql', '4.1.0'

mod 'camptocamp-augeas', '0.3.2'
mod 'stankevich-python', '1.7.16'

# Require updated versions

# Aethylred's modules
mod 'Aethylred-puppet', '1.4.1'
mod 'Aethylred-puppetdashboard', '1.0.7'
mod 'Aethylred-git', '0.3.1'
mod 'Aethylred-gitlab', '0.5.4'
